# -*- coding: utf-8 -*-

_version = '#sspaplotversion#'

_disclaimer = """
####Disclaimer
SSP&A's software is provided "AS IS", without warranty
of any kind, including, without limitation, the
warranties of merchantability, fitness for a particular
purpose and non-infringement. We request only that
application of the software and production of results
using the code is accompanied by a suitable
acknowledgment. The entire risk and responsibility as
to the quality and performance of the Software is borne
by the user. SSP&A disclaims all other warranties.
"""

_download = f"""
####Download
[version: {_version}](downloads/chump_{_version}.7z)
"""

__doc__ = f"""
###Configurable Handler for Universal Model Postprocessing

                 Developer: mou@sspa.com

                  version: {_version}

Hydrologic models are becoming increasingly complex with the
development of model codes and abundant data collection.
Efficient model and data processing and visualization are
needed to improve data analyses and model performance. The
use of automated scripted workflows has gained widespread
popularity due to its efficiency and capability of handling
large and varied datasets. However, despite the benefits of
automated workflows, their implementation can be impeded by
a steep learning curve, significant overhead investment at
the project outset, and other programming-related difficulties.
To address these challenges, a Configurable Universal Model
Post-processor (CHUMP) was developed as a framework for
post-processing data and model results. CHUMP simplifies the
process by using a configuration file that uses intuitive
keywords to specify a set of parameters that define data
abstraction and manipulation. It provides great coding-level
flexibility without the need of excessive programing knowledge.
The application of CHUMP is demonstrated through four examples
that postprocess model simulation and create figures and
animations of results generated by the different model codes.


""" + _disclaimer + _download

_cmd_head_ = f"""
========================= CHUMP =========================
 Configurable Handler for Universal Model Postprocessing
                 Developer: mou@sspa.com
                  version: {_version}
""" + _disclaimer + """
========================= CHUMP =========================
"""
